apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 064869464632.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 064869464632.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 4ddf3e05
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
